---
- name: Install MySQL
  hosts: mysqlserver
  user: obabb
  become: true
  become_user: root
  vars:
    MySQL_root_pass: Azertyuiop1234
  tasks:
    - name: Test installation
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      with_items:
        - mysql-server
        - mysql-client
        - python3-mysqldb
    - name: Creat Mysql database
      mysql_db:
        name: testdb
        state: present
        login_user: root
        login_password: Azertyuiop1234





ansible-playbook -i mon_inventaire.ini roles/mysqlDB.yaml -vvv
