- name:              install apache2
  remote_user:                                        azureuser
  hosts:                                              mysqlserver
  become:                                                  true
  become_user:                                             root
  gather_facts:                                            true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present
      become: yes
